### ISSUE TITLE
Continue after rerunning efficiently?

### ISSUE THREAD

**Issue by SupertigerDev** [michaeldzjap/rand-seed#18]
Is there anyway to continue the sequence after restarting the program?

eg:

```
const rand = new Rand('1234');
rand.next(); // 1
rand.next(); // 2

// restart program
const rand = new Rand('1234', sequence = 2);
rand.next(); // 3
...
```

I could run loops to do this, but that feels inefficient, especially if next is called a lot of times.

**Comment by michaeldzjap** [comment]
No. That would require some kind of offline memory storage to remember the state of one of the used [algorithms](https://github.com/michaeldzjap/rand-seed/tree/master/src/Algorithms) and that is out of the scope of this package.

What potentially would be possible to do is to provide public getters and setters for the state of the algorithms so you would be able to store and recover this yourself. How you would store this information you'd have to figure out yourself though, again that's not something I would want to bake into this package.

**Comment by SupertigerDev** [comment]
I see, thanks anyway. I think i found another package that allows me to store the state.
