### ISSUE TITLE
Current Xoshiro128ss implementation is based on an incorrect version 1.0

### ISSUE THREAD

**Issue by rinart73** [michaeldzjap/rand-seed#8]
Current library implementation: https://github.com/michaeldzjap/rand-seed/blob/develop/src/Algorithms/Xoshiro128ss.ts#L40
Current version 1.1 written in C: https://xoshiro.di.unimi.it/xoshiro128starstar.c

There are 2 major differences:

1. Version 1.0 generated new number based on `s[0]` (`this.a`), rather than `s[1]` (`this.b`). This is explicitly marked as a mistake that they fixed:
>  Note that version 1.0 had mistakenly s[0] instead of s[1] as state word passed to the scrambler.
2.  Rotl operation performed on generated number `r` has incorrect order of operations:
```typescript
// current
r = (r << 7) | ((r >>> 25) * 9);
// proper
r = ((r << 7) | (r >>> 25)) * 9;
```

With changes applied new implementation will of course generate different numbers for the same seeds, **which means it's not backwards compatible**.

**Comment by michaeldzjap** [comment]
Thanks for reporting @rinart73 . Will pick this up as soon as I have time.
